import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Adsence from "./components/Adsence";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MY GEM - Your personal AI assistant...",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="dark" lang="en">
      <head>
        <Adsence />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
